baseURL = "/"
locale = "en-us"
relativeURLs = true
publishDir = "docs"
title = "Trevor Kasuku"
copyright = "Trevor Kasuku"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Blogs"
url = "/blogs/"
weight = 3

[[menu.main]]
name = "Classes"
url = "/classes/"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  description = """I am a distributed systems engineer at Apple working in a platform/infra team. Our platform is data-intensive and supports ~3B customers. My core skills are in distributed systems algorithms, multi-threaded programming, and data storage systems.

This site is a portfolio of my advanced coursework, projects built from scratch (as Karpathy intended), and blogs explaining my understanding of the concepts I have learned with no jargon (as Feynman intended).
"""
